### ISSUE TITLE
Bug khi chết vì deny (có thể là do âm máu cx bug)

### ISSUE THREAD

**Issue by Neokun** [giangm9/enduel#10]
![capture](https://user-images.githubusercontent.com/25172258/33992494-6ab64a06-e105-11e7-8733-7aa2cfd1d23f.PNG)

**Comment by giangm9** [comment]
đã sửa bug này, nguyên nhân là do endgame nhưng Player vẫn cố emit cho OP từ cuối cùng mà Player sử dụng
Cái này hiện tại đã bỏ việc player gửi từ cuối cùng, tuy nhiên về sau vẫn nên giữ lại để người chơi biết từ mà đối thủ sử dụng là từ gì
