### ISSUE TITLE
Chống lặp Deny + TimeOut loop

### ISSUE THREAD

**Issue by giangm9** [giangm9/enduel#5]
Việc 2 bên deny nhau liên tục dẫn đến tạo ra một vòng lặp vô hạn, thay đổi luật chơi để chống chuyện đó xảy ra

**Comment by giangm9** [comment]
đang làm issue này

**Comment by Neokun** [comment]
đang làm cái nào thì cứ tự assign bản thân vào là được :v, ko cần thông báo đâu =))

**Comment by giangm9** [comment]
đã fix
