### ISSUE TITLE
Thiết kế lại tìm được trận lúc ấn ACCEPT -> ACCEPTED

### ISSUE THREAD

**Issue by Neokun** [giangm9/enduel#9]
để ACCECT bthg gây bối rối ko biết ấn được chưa
khi ấn được chuyển thành accepted và có nếu chữ waiting for opponent thì tốt

**Comment by giangm9** [comment]
Bổ sung thêm là cái nút X làm cho nhỏ lại để tránh người dùng bấm nhầm, task này dễ, ai nhận không ?
